name: aig
raw_data_dir: ../../local_tryout_data/EPFL/adder
processed_data_dir: ''
tokenizer_path: ./dataset/tokenizer
block_size: 512
pad_value: -100
max_node_count: 56
val_split_ratio: 0.1
test_split_ratio: 0.1
pi_counts:
  min: 2
  max: 12
po_counts:
  min: 2
  max: 7
and_counts:
  min: 3
  max: 44
tokens:
  node_types:
  - NODE_CONST0
  - NODE_PI
  - NODE_AND
  - NODE_PO
  edge_types:
  - EDGE_REG
  - EDGE_INV
vocab_size: 72
edge_counts:
  min: 9
  max: 95
